skip  now ignores jumps
pharo-spec/ScriptableDebugger pull request #54
Opened 2022-10-21 14:58 UTC by adri09070

Fixes #51.

skip used to step over jump bytecodes. Notably, if a comparison before a ìfTrue:ifFalse:`message was skipped, it used to skip the comparison and then step the jumpIfFalse bytecode. As this bytecode expected a boolean on the stack (the result of the comparison that has been skipped) and as the result on the stack is (probably) not a boolean, an exception `MustBeBoolean` was raised and  was not handled. As a result, `skipUpTo` entered an infinite loop because we would never reach the aimed node.

Now, skips stops on jump bytecodes (notably on ìfTrue:ifFalse` messages) and manages these bytecodes separately: it pops the argument if it has one (this is the case for jumpTrue: and jumpFalse: bytecodes) and it simply does not execute the jump bytecode. Then, it steps to the first next interesting bytecode (I reimplemented this function in `DebugSession` to stop on jump bytecodes

2022-10-28 07:47 UTC, adri09070 commented
Failing test does not seem related.

2022-11-18 14:30 UTC, StevenCostiou requested changes

2022-11-18 14:30 UTC, StevenCostiou commented on Sindarin/SindarinDebugger.class.st
> +	self node isBlock ifTrue: [ ^ self skipBlockNode ].
Replace by db dispatch

2022-11-18 14:30 UTC, StevenCostiou commented on Sindarin/SindarinDebugger.class.st
> +			 instructionStream willJumpIfTrue ] ]) ifTrue: [ ^ self skipJump ].
refactor in InstructionStream>>willJump

2022-11-18 14:30 UTC, StevenCostiou commented on Sindarin/SindarinDebugger.class.st
>  		 nextBytecode bytes first between: 88 and: 94 ]) ifTrue: [
= instructionSteram willReturn

2022-11-25 11:57 UTC, adri09070 commented
It fails because of a fuel test and other tests ... so not related

2023-02-06 14:01 UTC, merged