Sindarin extracting core
pharo-spec/ScriptableDebugger pull request #61
Opened 2023-03-23 09:09 UTC by adri09070

- moving SindarinDebugSession and SindarinDebugger to Sindarin-Core package
- All methods doing things about core concepts became extension methods of SindarinDebugger
- Setting flags for TODOs
- refactoring methods to use the Sindarin API within Sindarin
- extracting methods from longer methods
- removing unused methods
- renaming unclear methods
- categorizing uncategorized classes

2023-03-23 09:10 UTC, adri09070 commented
There's something that bothers me. Iceberg doesn't want to commit the deletion of the class `SindarinDebugger` from the package `Sindarin-Core`

2023-03-30 14:29 UTC, adri09070 commented
Ah, here it goes! Don't bother about the last 5 commits

2023-03-31 14:19 UTC, StevenCostiou requested changes

2023-03-31 14:19 UTC, StevenCostiou commented on src/Sindarin/TSindarin.trait.st
> +	^ #( 70 71 79 148 160 )
Reference to the VM repo where those primitive numbers are indicated.

2023-05-10 09:15 UTC, merged